# Generated by Django 4.2.14 on 2024-07-19 01:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gourmetguide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo'),
        ),
    ]
